### ISSUE TITLE
goal: spipo.co.uk

### ISSUE THREAD

**Issue by OskarZyg** [Puyodead1/spipo-comunity#5]
https://domains.google.com/registrar/search?searchTerm=spipo.co.uk&hl=en
https://domains.google.com/registrar/search?searchTerm=spipo.uk&hl=en

**Comment by redaam** [comment]
you using google domains? really

**Comment by redaam** [comment]
namecheap exists

**Comment by Puyodead1** [comment]
lol wtf

**Comment by redaam** [comment]
FYI spipo.net is available AND cheaper
